ALTER SESSION SET CONTAINER = FREEPDB1;
-- CREATE USER TEST IDENTIFIED BY myPwd QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO myUser;
CREATE SCHEMA AUTHORIZATION myUser;
ALTER SESSION SET CURRENT_SCHEMA = myUser;

CREATE TABLE FESTIVO (
  FECHA   DATE    NOT NULL
);
