name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Oracle
      uses: gvenzl/setup-oracle-free@v1
      with:
        container-name: oracle
        container-runtime: docker
        app-user: myUser
        app-user-password: myPwd
        health-interval: 10s
        health-max-retries: 20
        setup-scripts: ${{ github.workspace }}/scripts

    - name: Check Oracle container
      run: |
        docker container ls
        if [[ $(docker inspect -f {{.State.Running}} oracle) != "true" ]]; then
          echo "[ERR] oracle container not running!"
          exit 1
        else
          echo "[INF] oracle container is running!"
          docker container logs oracle
        fi

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      env:
        TZ: 'Europe/Madrid'
      run: |
        date
        mvn -B test --file pom.xml
