name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Oracle container
      uses: gvenzl/setup-oracle-free@v1
      with:
        container-runtime: docker
        app-user: app_user
        app-user-password: app_user_password
        health-interval: 10s
        health-max-retries: 20
        setup-scripts: ${{ github.workspace }}/scripts

    - name: Check Oracle container logs for errors
      run: |
        docker container ls
        docker container logs oracle | tee -a /tmp/oracle.log
        if grep 'ERROR' /tmp/oracle.log >/dev/null; then
          echo "[ERR] Something went wrong!"
          echo "[ERR] See above logs for more details."
          exit 1
        fi
        echo "[INF] orcale container started successfully!"

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: maven

    - name: Build with Maven
      env:
        TZ: Europe/Madrid
      run: mvn -B test --file pom.xml
